### ISSUE TITLE
Question about why not use apache2_module

### ISSUE THREAD

**Issue by ricardofontanelli** [weareinteractive/ansible-apache2#5]
Hi, I would like to know why you are not using the native core module [apache2_module](https://github.com/ansible/ansible-modules-core/blob/devel/web_infrastructure/apache2_module.py) to enable apache modules? I'm building a role to configure apache2 (using this native module), but I'm having some problems to run it on TraveisCI (but not in my local machine running vagrant).

**Comment by franklinkim** [comment]
Hey, yeah, good point. I used to NOT using the build in apache2_module because it used to support Ubuntu trusty and precise. The apache2_module is only available since trusty so in order to keep it simple I still used the manual way (forgot to refactor this).

Probably this is also why your Travis is failing... can you check the Travis Ubuntu version you're testing against?

**Comment by ricardofontanelli** [comment]
Thanks a lot for your attention @franklinkim, I'm using Ubuntu Trusty on TravisCI, and it doesn't work too, but I'll try to use the shell instead apache2_module!
